config/routes.rb
DirectorioszapotlanCom::Application.routes.draw do
  resources :businesses

end

app/models/business.rb
class Business < ActiveRecord::Base
attr_accessible :address, :cellphone, :city, :description, :email, :keywords, :name, :phone, :website

	def self.search(search)
		if search
			find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  # GET /businesses
  # GET /businesses.json

 def index 
      if params[:search].nil? 
        @businesses = []
      else
        @businesses = Business.search(params[:search])
      end
        respond_to do |format|
            format.html # index.html.erb
            #format.json { render json: @businesses }
        end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @business = Business.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @business }
    end
  end

  # GET /businesses/new
  # GET /businesses/new.json
  def new
    @business = Business.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @business }
    end
  end

  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(params[:business])

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        #format.json { render json: @business, status: :created, location: @business }
      else
        format.html { render action: "new" }
        #format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /businesses/1
  # PUT /businesses/1.json
  def update
    @business = Business.find(params[:id])

    respond_to do |format|
      if @business.update_attributes(params[:business])
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url }
      #format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :cellphone %><br />
    <%= f.text_field :cellphone %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_area :keywords %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<%= stylesheet_link_tag "styles" %>
<!--[if lt IE 7]>
<style media="screen" type="text/css">

#container {
  height:100%;
}

</style>
<![endif]-->

<div id="header">
<div id="menu">
<ul>
    <li><a href="registrar/">Registrar Negocio</a></li>
    <li><a href="contacto/">Contacto</a></li>
    <li><a href="accesar/">Accesar</a></li>
</ul>
</div>
<div id="social"><span id="facebook">
<a href="http://facebook.com/">
<%= image_tag "facebook.png", :size => "26x26" , :alt => "facebook"  %></a></span> 

<span id="twitter"><a href="http://twitter.com/">
<%= image_tag "twitter.png", :size => "26x26" , :alt => "twitter"  %></a></span>
</a></span></div>
</div>
<div id="center">
    <div id="logo"><%= image_tag "encuentralomejorlogo.png", :alt => "directorioszapotlan"  %></div>
    <div id="searchbox">
    
    <%= form_tag businesses_path, method: 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "", name: nil , :id => "searchbutton"  %>
<% end %>

    <!-- <input type="text" name="search" id="search" value="Busqueda" class="clearme"> <input type="submit" id="searchbutton" value=""/> -->
    

    </div>
</div>

<% for business in @businesses %>
  <%= link_to business.name, business_path(business) %><br>
  <%= business.description %><br>
  <%= business.website %><br>
  <%= business.city %><br>
  <%= business.email %><br>
  <%= business.phone %><br>
  <%= business.cellphone %><br>
  <%= business.address %><br>
  <%= link_to "Edit", edit_business_path(business) %>
  <%= link_to "Destroy", business_path(business), method: :delete %>
  <hr>
<% end %>


<%= link_to 'New Business', new_business_path %>

<div id="footer">www.encuentralomejor.com Todos los derechos reservados &copy; 2012 Desarollado por <a href="http://morphcom.com">Cesar Gaytán</a></div>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @business.name %>
</p>

<p>
  <b>Description:</b>
  <%= @business.description %>
</p>

<p>
  <b>Website:</b>
  <%= @business.website %>
</p>

<p>
  <b>City:</b>
  <%= @business.city %>
</p>

<p>
  <b>Email:</b>
  <%= @business.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @business.phone %>
</p>

<p>
  <b>Cellphone:</b>
  <%= @business.cellphone %>
</p>

<p>
  <b>Keywords:</b>
  <%= @business.keywords %>
</p>

<p>
  <b>Address:</b>
  <%= @business.address %>
</p>


<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DirectorioszapotlanCom</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>